version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one
    ports: 
      - 16686:16686
      - 14268:14268
      - 14250:14250
    deploy:
      restart_policy:
        condition: on-failure
  collector-gateway:
    image: otel/opentelemetry-collector:0.52.0
    volumes: 
      - ./extra/collector.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318"
    depends_on:
      - jaeger
